import type { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Xbox 360 Wireless Controller',
    slug: 'xbox-360-wireless-controller',
    description: 'The iconic Xbox 360 Wireless Controller offers precision, comfort, and control. Featuring integrated 2.4 GHz high-performance wireless technology and a sleek ergonomic design.',
    price: 2000,
    original_price: null,
    category: 'Controllers',
    image_url: '/products/xbox-360-controller.jpg',
    variants: JSON.stringify([
      { id: 'v1', name: 'Carbon Black', image_url: '/products/xbox-360-controller.jpg', color: '#080808', glow: 'rgba(255, 255, 255, 0.15)' },
      { id: 'v2', name: 'Cyan', image_url: '/products/glow-cyan.jpg', color: '#00f0ff', glow: 'rgba(0, 240, 255, 0.5)' },
      { id: 'v3', name: 'Blue', image_url: '/products/glow-blue.jpg', color: '#0047AB', glow: 'rgba(0, 71, 171, 0.5)' },
      { id: 'v4', name: 'Green', image_url: '/products/glow-green.jpg', color: '#00ff41', glow: 'rgba(0, 255, 65, 0.5)' },
      { id: 'v5', name: 'Pink', image_url: '/products/glow-pink.jpg', color: '#ff00ff', glow: 'rgba(255, 0, 255, 0.6)' }
    ]),
    badge: 'CLASSIC',
    rating: 4.9,
    review_count: 5120,
    in_stock: 1,
    featured: 1,
    platform: 'PC, Xbox 360',
    genre: 'Input Device',
    brand: 'Xbox'
  },
  {
    id: 'p2',
    name: 'Redragon K670 Argo',
    slug: 'redragon-k670-argo',
    description: '75% Wireless Mechanical Keyboard with Gasket Mount and RGB lighting. Designed for the ultimate typing and gaming experience.',
    price: 1695,
    original_price: null,
    category: 'Mechanical Keyboards',
    image_url: 'https://redragonshop.com/cdn/shop/products/ArgoK670_1_800x.png',
    variants: JSON.stringify([
      { id: 'v1', name: 'Argo Edition', image_url: 'https://redragonshop.com/cdn/shop/products/ArgoK670_1_800x.png', color: '#ff8c00', glow: 'rgba(255, 140, 0, 0.4)' }
    ]),
    badge: 'NEW',
    rating: 4.8,
    review_count: 850,
    in_stock: 1,
    featured: 1,
    platform: 'PC, Mac',
    genre: 'Keyboard',
    brand: 'Redragon'
  },
  {
    id: 'p3',
    name: 'Logitech G Pro X Superlight',
    slug: 'logitech-g-pro-x-superlight',
    description: 'Ultra-lightweight wireless gaming mouse with HERO 25K sensor. Designed with top esports pros for maximum performance.',
    price: 6895,
    original_price: null,
    category: 'Gaming Mouse',
    image_url: 'https://resource.logitechg.com/w_692,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-superlight/pro-x-superlight-black-gallery-1.png?v=1',
    variants: JSON.stringify([
      { id: 'v1', name: 'Superlight Black', image_url: 'https://resource.logitechg.com/w_692,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-superlight/pro-x-superlight-black-gallery-1.png?v=1', color: '#0f0f0f', glow: 'rgba(255, 255, 255, 0.2)' }
    ]),
    badge: 'ELITE',
    rating: 4.9,
    review_count: 12400,
    in_stock: 1,
    featured: 1,
    platform: 'PC',
    genre: 'Mouse',
    brand: 'Logitech'
  },
  {
    id: 'p4',
    name: 'CS2 Dragon Lore Wireless Mouse',
    slug: 'cs2-dragon-lore-wireless-mouse',
    description: 'Premium wireless gaming mouse featuring the legendary CS2 Dragon Lore skin design. Equipped with an ultra-low latency wireless connection and precision gaming sensor.',
    price: 5123.11,
    original_price: null,
    category: 'Gaming Mouse',
    image_url: 'https://media.steelseriescdn.com/thumbs/catalog/items/63391/798402f12255476a80436d4df6c5478d.png.350x280_q100_crop-fit_optimize.png',
    badge: 'DRAGON LORE',
    variants: '[]',
    rating: 4.9,
    review_count: 8900,
    in_stock: 1,
    featured: 1,
    platform: 'PC, Mac, Linux',
    genre: 'Mouse',
    brand: 'SteelSeries'
  },
  {
    id: 'p5',
    name: 'HyperX Cloud Alpha',
    slug: 'hyperx-cloud-alpha',
    description: 'Durable aluminum frame, detachable cable, and dual chamber drivers for more distinction and less distortion. Designed for pro-level gaming comfort.',
    price: 4395,
    original_price: null,
    category: 'Headsets',
    image_url: 'https://hyperx.com/cdn/shop/products/hyperx_cloud_alpha_1_800x.png',
    variants: JSON.stringify([
      { id: 'v1', name: 'Alpha Edition', image_url: 'https://hyperx.com/cdn/shop/products/hyperx_cloud_alpha_1_800x.png', color: '#ff3131', glow: 'rgba(255, 49, 49, 0.4)' }
    ]),
    badge: 'PRO CHOICE',
    rating: 4.8,
    review_count: 8500,
    in_stock: 1,
    featured: 1,
    platform: 'PC, PS5, Xbox, Switch',
    genre: 'Audio',
    brand: 'HyperX'
  },
  {
    id: 'p6',
    name: 'PlayStation 5 Console',
    slug: 'playstation-5',
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
    price: 40032,
    original_price: null,
    category: 'Consoles',
    image_url: 'https://gmedia.playstation.com/is/image/SIEPDC/ps5-product-thumbnail-01-en-14sep21?$facebook$',
    variants: JSON.stringify([
      { id: 'v1', name: 'Standard Edition', image_url: 'https://gmedia.playstation.com/is/image/SIEPDC/ps5-product-thumbnail-01-en-14sep21?$facebook$', color: '#ffffff', glow: 'rgba(255, 255, 255, 0.5)' }
    ]),
    badge: 'NEXT GEN',
    rating: 4.9,
    review_count: 45000,
    in_stock: 1,
    featured: 0,
    platform: 'PS5',
    genre: 'Console',
    brand: 'Sony'
  },
  {
    id: 'p7',
    name: 'SteelSeries Gaming Mouse Pad',
    slug: 'steelseries-gaming-mouse-pad',
    description: 'Elite cloth gaming mousepad with dynamic 2-zone RGB backlighting. The choice of esports pros for precision and control.',
    price: 3085.96,
    original_price: null,
    category: 'Accessories',
    image_url: 'https://media.steelseriescdn.com/thumbs/catalog/items/63391/798402f12255476a80436d4df6c5478d.png.350x280_q100_crop-fit_optimize.png',
    badge: 'RGB ELITE',
    variants: '[]',
    rating: 4.9,
    review_count: 12000,
    in_stock: 1,
    featured: 1,
    platform: 'Desktop',
    genre: 'Surface',
    brand: 'SteelSeries'
  }
];
